version: "2"

services:
  ejbca:
          #  build: .
    image: primekey/ejbca-ce:latest 

    container_name: ejbca
    volumes:
      - ./secrets:/run/secrets
      - ./ejbca:/var/lib/ejbca
    environment:
      TZ: "UTC"

      MYSQL_CONNECTION_URL: mysql://mariadb:3306/ejbca
      MYSQL_USERNAME: ejbca
      MYSQL_USERNAME_SECRET: /run/secrets/ejbca.mysql_username
      MYSQL_PASSWORD: letmein1
      MYSQL_PASSWORD_SECRET: /run/secrets/ejbca.mysql_password
      EJBCA_DATABASE_PASSWORD: "p@nd0r@"
      EJBCA_DATABASE: "ejbca"
      EJBCA_DATABASE_USERNAME: "root"
      WILDFLY_SERVER_CN: ejbca
      WILDFLY_SERVER_ALT_NAMES:
      #WILDFLY_STOREPASS_SECRET: /run/secrets/ejbca.wildfly_storepass
      #WILDFLY_TRUSTSTOREPASS_SECRET: /run/secrets/ejbca.wildfly_truststorepass

      SMTPSERVER_ENABLED: "true"
      SMTPSERVER_FROM: ejbca-noreply@ejbca
      SMTPSERVER_USE_TLS: "false"
      SMTPSERVER_HOST: smtp
      SMTPSERVER_PORT: 25
      EJBCA_DATABASE_HOST: mariadb
      SMTPSERVER_AUTH_REQUIRED: "true"
      SMTPSERVER_USERNAME: josh
      SMTPSERVER_PASSWORD: testing
      #SMTPSERVER_USERNAME_SECRET: /run/secrets/ejbca.smtpserver_username
      #SMTPSERVER_PASSWORD_SECRET: /run/secrets/ejbca.smtpserver_password

      CA_NAME: Root Certificate Authority
      CA_DN: CN=Root Certificate Authority
      CA_KEYTYPE: RSA
      CA_KEYSPEC: 2048
      CA_SIGNATUREALGORITHM: SHA256WithRSA
      CA_VALIDITY: 7300
      CA_POLICY: "null"
      #CA_PASSWORD_SECRET: /run/secrets/ejbca.ca_password

      #SUPERADMIN_CN_SECRET: /run/secrets/ejbca.superadmin_cn
      #SUPERADMIN_DN_SECRET: /run/secrets/ejbca.superadmin_dn
      #SUPERADMIN_PASSWORD_SECRET: /run/secrets/ejbca.superadmin_password
    networks:
      ejbca-net:
        ipv4_address: 173.18.4.4


    expose:
      - 8080
      - 8442
    ports:
      - "8443:8443"
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
      - ./secrets:/run/secrets
    expose:
      - 3306
    environment:
      TZ: "UTC"
      EJBCA_DATABASE_PASSWORD: "p@nd0r@"
      EJBCA_DATABASE_USERNAME: "pandora"
      MYSQL_DATA_DIR: /var/lib/mysql
      MYSQL_ROOT_SECRET: /run/secrets/mysql.root
      MARIADB_ROOT_PASSWORD: "p@nd0r@"
      #      MYSQL_ROOT_ALLOWED_HOSTS: "%"
      #      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      ejbca-net:
        ipv4_address: 173.18.4.3

  httpd:
    container_name: httpd
    image: wodby/apache
    volumes:
      - ./httpd:/etc/apache2/conf.d
    ports:
      - 8080:80
      - 4443:443
    environment:
      TZ: "UTC"
    networks:
      ejbca-net:
        ipv4_address: 173.18.4.2

networks:
  ejbca-net:
    ipam:
      config:
       - subnet: 173.18.4.1/24
         gateway: 173.18.4.1
